from django.contrib import admin

""" @file admin.py
    @author none (auto-generated by Django)
    @description Models updated through the admin panel are implemented here
"""

# Register your models here.
